import { useState, useEffect } from "react";
import FormField from "../../components/FormField";
import Loader from "../../components/Loader";
import RenderCard from "../../components/RenderCard";

let Home = () => {
  let [isLoading, setIsLoading] = useState(false);
  let [allPost, setAllPost] = useState([null]);
  let [searchText, setSearchText] = useState("");
  return (
    <>
      <section className="max-w-7x1 mx-auto">
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">
            The Community Showcase
          </h1>
          <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
            Browse through a collection of imaginative and stunning images
            generated by JARVIS-E AI (Clone of DALL-E AI)
          </p>
        </div>
        <div className="mt-16 ">
          <FormField />
        </div>
        <div className="mt-10">
          {isLoading ? (
            <div className="flex justify-center items-center">
              <Loader />
            </div>
          ) : (
            <>
              {searchText && (
                <h2 className="font-medium text-[#666e75] text-xl mb-3">
                  Showing result for{" "}
                  <span className="text-[#222328]"> {searchText} </span>
                </h2>
              )}
              <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 grid-3">
                {searchText ? (
                  <RenderCard data={[]} title="No search result found" />
                ) : (
                  <RenderCard data={[]} title="No post found" />
                )}
              </div>
            </>
          )}
        </div>
      </section>
    </>
  );
};
export default Home;
